### ISSUE TITLE
BI.RESTClient class missing

### ISSUE THREAD

**Issue by mdv10** [intersystems/Samples-BI#14]
The Samples-BI documentation mentions a BI.RESTClient class, but it doesn't exist - it's not part of the download. We should be able to export the Cache version of the class and rename it to use the Iris naming convention. I did some limited testing and it appeared to work as expected.

**Comment by bdeboe** [comment]
@lexiISC: Is this something we chose not to publish after all or did it slip through the cracks?

**Comment by mdv10** [comment]
Hello all! What is the status of this request? Thank you.

**Comment by bdeboe** [comment]
Looks like your PR was merged already a while ago with commit b2de5b0, Thanks!
