### ISSUE TITLE
failure to install outside docker

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems/Samples-BI#33]
>ver
zpm.0.3
load /backup/repo/Samples-BI

[samples-bi]    Reload START (/backup/repo/Samples-BI/)
[samples-bi]    Reload SUCCESS
[samples-bi]    Module object refreshed.
[samples-bi]    Validate START
[samples-bi]    Validate SUCCESS
[samples-bi]    Compile START
[samples-bi]    Compile SUCCESS
[samples-bi]    Activate START
[samples-bi]    Configure START
[samples-bi]    Configure FAILURE
[samples-bi]    Activate FAILURE
ERROR! ObjectScript error: <INVALID OREF>zStopJournalling+5^HoleFoods.Utils.1
refusal to install if not in IRISAPP

**Comment by evshvarov** [comment]
there is a parameter. IRISAPP is a default

**Comment by SergeyMi37** [comment]
It's clear. It needs to be improved so that there are no errors.

**Comment by evshvarov** [comment]
Agree
